Run "CommonUtilites/ApplicationUtilites".launch_App
"CommonUtilites/ApplicationUtilites". check_exisiting_Package_home
"CommonUtilites/ApplicationUtilites".open_icon_1_Home
"CommonUtilites/ApplicationUtilites".open_icon_2_Home
"CommonUtilites/ApplicationUtilites".open_OMart_Home
"CommonUtilites/ApplicationUtilites".Top_Up
"CommonUtilites/ApplicationUtilites". game_play
"CommonUtilites/ApplicationUtilites".mipsen_nav
